### ISSUE TITLE
Web: 10. Add "Label" when bring mouse on ICONS "Tool tip"

### ISSUE THREAD

**Issue by CarOnlineGuru** [CarOnlineGuru/CarOnlineGuruFrontEnd#10]

**Comment by sonalprajapati** [comment]
can you give me places of lablels? and their text i have to add

**Comment by CarOnlineGuru** [comment]
Please left this option, right now we dont need to add this, later we will do in next phase

**Comment by CarOnlineGuru** [comment]
the RED circled option is automatically hiding sometimes, when you go to other slides and comaback

![image](https://cloud.githubusercontent.com/assets/25733412/23116638/86baa8b4-f786-11e6-94f7-4593e859b90b.png)
